name: Zvonko CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Software\Zvonko\Zvonko.sln
      IntegrationTests_Project_Path: Software\Zvonko\IntegrationTests\IntegrationTests.csproj
      UnitTests_Project_Path: Software\Zvonko\UnitTests\UnitTests.csproj
      Artifact_Directory: Software\Zvonko\Zvonko\bin\Release  # Adjust this path to your actual output directory

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 4.8.x

    - name: Navigate to root folder
      run: cd $GITHUB_WORKSPACE

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages and build solution
    - name: Restore and Build
      run: |
        msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform="Any CPU"

    # Execute unit tests
    - name: Run Unit Tests
      run: dotnet test $env:UnitTests_Project_Path --configuration $env:Configuration

    # Execute integration tests
    - name: Run Integration Tests
      run: dotnet test $env:IntegrationTests_Project_Path --configuration $env:Configuration

    # Publish WPF application
    - name: Publish WPF Application
      run: |
        msbuild $env:Solution_Name /t:Publish /p:Configuration=$env:Configuration /p:Platform="Any CPU"

    # Upload built artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: WPF-Application
        path: $env:Artifact_Directory
