name: Build solution and Create Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore Software\Zvonko\Zvonko.sln

      - name: Create Publish Directory
        run: mkdir -p Software\Zvonko\publish

      - name: Navigate to Solution Directory
        run: cd Software\Zvonko

      - name: Publish Zvonko.exe
        run: msbuild /t:Publish /p:Configuration=Release /p:PublishDir=publish Zvonko.sln

      - name: Navigate back to working directory
        run: cd ..

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ github.token }} 
          prerelease: false
          files: |
            Software\Zvonko\publish\Zvonko.exe
