name: Build and Publish Zvonko

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore Software\Zvonko\Zvonko.sln

      - name: Create Publish Directory
        run: mkdir Software\Zvonko\publish

      - name: Build Zvonko.exe
        run: |
          msbuild /t:Publish /p:Configuration=Release /p:PublishDir=Software\Zvonko\publish Zvonko.sln

      - name: List publish directory contents
        run: dir Software\Zvonko\publish  
        
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ github.token }}
          prerelease: false
          files: |
            Software\Zvonko\publish\Zvonko.exe
