name: Build solution and Create Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore Software\Zvonko\Zvonko.sln

      - name: Build with MSBuild
        run: msbuild /p:configuration=Release /p:platform="Any CPU" /p:outputpath="bin/" Software\Zvonko\Zvonko.sln

      - name: Create Publish Directory
        run: mkdir -p Software\Zvonko\publish

      - name: Publish Zvonko.exe
        run: msbuild /t:Publish /p:Configuration=Release /p:PublishDir=Software\Zvonko\publish/

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ github.token }}  
          prerelease: false
          files: |
            Software\Zvonko\publish\Zvonko.exe
