name: Build solution on push

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore Software\Zvonko\Zvonko.sln

    - name: Build with MSBuild
      run: msbuild /p:configuration=Debug /p:platform="Any CPU" /p:outputpath="bin/" Software\Zvonko\Zvonko.sln
